version: '3'

volumes:
  database_savings:
  server_savings:
services:
  mdb:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
    volumes:
      - database_savings:/data/db
    ports:
      - "27017:27017"
  server:
    image: goportfolio
    environment:
      MDB_ROOT_USERNAME: root
      MDB_ROOT_PASSWORD: root_password
      ADMIN_PASSWORD: 123456
      # TODO: Change this to release
      GIN_MODE: debug
    volumes:
      - server_savings:/app/data
    ports:
      - "9000:9000"
    depends_on:
      - mdb
    links:
      - mdb
    build: .
    working_dir: /app/data
